development:
  adapter: postgresql
  database: guia_venda_mais_development
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

test: &test
  adapter: postgresql
  database: guia_venda_mais_test
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: guia_venda_mais_production
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0